#!/bin/bash

#SBATCH --partition=1080ti-long
#SBATCH --gres=gpu:1
#SBATCH --time=7-00:00
#SBATCH --mem=60000

# ~/anaconda3/bin/python ./src/testing/summarization/cnn_dm_pyrouge.py --input ./data/src/claim_inputs/rand_cit_title_full_w_sec --checkpoint ./models/czi_neuro100-20200308-163129 --method_set ours --dict ./data/dictionary_index --n_basis 10 --emsize 200 --max_sent_len 512 --outf_vis eval_log/summ_vis/ours_claim.json

# ~/anaconda3/bin/python ./src/testing/summarization/cnn_dm_pyrouge.py --input ./data/src/claim_inputs/rand_cit_title_full_w_sec --checkpoint ./models/czi_neuro100-20200301-223241 --method_set ours+bert+embs --top_k_max 5 --dict ./data/dictionary_index --n_basis 100 --emsize 200 --max_sent_len 50 --outf_vis eval_log/summ_vis/claim_bert_new.json
# ~/anaconda3/bin/python ./src/testing/summarization/cnn_dm_pyrouge.py --input ./data/src/claim_inputs/rand_cit_title_full_w_sec --checkpoint ./models/czi_neuro100-20200301-223241 --method_set ours --dict ./data/dictionary_index --n_basis 100 --emsize 200 --max_sent_len 512 --outf_vis eval_log/summ_vis/ours100_claim.json
# ~/anaconda3/bin/python ./src/testing/summarization/cnn_dm_pyrouge.py --input ./data/src/claim_inputs/rand_cit_title_full_w_sec --checkpoint ./models/czi_neuro100-20200301-223241 --method_set ours+bert+embs --top_k_max 4 --dict ./data/dictionary_index --bert_dict ./data/processed/czi_bert_min100/dictionary_index --n_basis 100 --emsize 200 --max_sent_len 50 --outf_vis eval_log/summ_vis/claim_results.json --section_set results
# ~/anaconda3/bin/python ./src/testing/summarization/cnn_dm_pyrouge.py --input ./data/src/claim_inputs/rand_cit_title_full_w_sec --checkpoint ./models/czi_neuro100-20200301-223241 --method_set ours+bert+embs --top_k_max 4 --dict ./data/dictionary_index --bert_dict ./data/processed/czi_bert_min100/dictionary_index --n_basis 100 --emsize 200 --max_sent_len 50 --outf_vis eval_log/summ_vis/claim_abstract.json --section_set abstract
# ~/anaconda3/bin/python ./src/testing/summarization/cnn_dm_pyrouge.py --input ./data/src/claim_inputs/sample --checkpoint ./models/czi_neuro100-20200301-223241 --method_set ours+bert+embs --top_k_max 4 --dict ./data/dictionary_index --bert_dict ./data/processed/czi_bert_min100/dictionary_index --n_basis 100 --emsize 200 --max_sent_len 50 --outf_vis eval_log/summ_vis/claim_abstract.json --section_set abstract
# ~/anaconda3/bin/python ./src/testing/summarization/cnn_dm_pyrouge.py --input ./data/src/claim_inputs/rand_cit_title_full_w_sec --checkpoint ./models/czi_neuro100-20200301-223241 --method_set ours+bert+embs --top_k_max 2 --dict ./data/dictionary_index --bert_dict ./data/processed/czi_bert_min100/dictionary_index --n_basis 100 --emsize 200 --max_sent_len 50 --outf_vis eval_log/summ_vis/claim_results_random.txt --section_set results --output_order random
# ~/anaconda3/bin/python ./src/testing/summarization/cnn_dm_pyrouge.py --input ./data/src/claim_inputs/rand_cit_title_full_w_sec --checkpoint ./models/czi_neuro100-20200301-223241 --method_set ours+bert+embs --top_k_max 2 --dict ./data/dictionary_index --bert_dict ./data/processed/czi_bert_min100/dictionary_index --n_basis 100 --emsize 200 --max_sent_len 50 --outf_vis eval_log/summ_vis/claim_abstract_random.txt --section_set abstract --output_order random
# ~/anaconda3/bin/python ./src/testing/summarization/cnn_dm_pyrouge.py --input ./data/src/claim_inputs/rand_cit_title_full_w_sec --checkpoint ./models/czi_neuro100-20200301-223241 --method_set ours+sentvec --top_k_max 2 --dict ./data/dictionary_index --bert_dict ./data/processed/czi_bert_min100/dictionary_index --n_basis 100 --emsize 200 --max_sent_len 50 --outf_vis eval_log/summ_vis/claim_results_sentvec.txt --section_set results
# ~/anaconda3/bin/python ./src/testing/summarization/cnn_dm_pyrouge.py --input ./data/src/claim_inputs/rand_cit_title_full_w_sec --checkpoint ./models/czi_neuro100-20200301-223241 --method_set ours+bert+embs+sentvec --top_k_max 9999 --dict ./data/dictionary_index --bert_dict ./data/processed/czi_bert_min100/dictionary_index --n_basis 100 --emsize 200 --max_sent_len 50 --outf_vis eval_log/summ_vis/claim_all.txt --section_set results --num_files 23
~/anaconda3/bin/python ./src/testing/summarization/cnn_dm_pyrouge.py --input ./data/src/claim_inputs/rand_cit_title_full_w_sec --checkpoint ./models/czi_neuro100-20200301-223241 --method_set ours+embs --top_k_max 9999 --dict ./data/dictionary_index --bert_dict ./data/processed/czi_bert_min100/dictionary_index --n_basis 100 --emsize 200 --max_sent_len 50 --outf_vis eval_log/summ_vis/claim_all.txt --section_set results --num_files 23
