#!/bin/bash

#SBATCH --partition=1080ti-long
#SBATCH --gres=gpu:1
#SBATCH --time=7-00:00
#SBATCH --mem=60000

# ~/anaconda3/bin/python ./src/testing/summarization/cnn_dm_pyrouge.py --input ./data/src/summ_inputs/abstract/ --checkpoint ./models/czi_neuro100-20200308-163129 --method_set ours+embs --dict ./data/dictionary_index --n_basis 10 --emsize 200
# ~/anaconda3/bin/python ./src/testing/summarization/cnn_dm_pyrouge.py --input ./data/src/summ_inputs/sample/ --checkpoint ./models/czi_neuro100-20200308-163129 --method_set ours+embs --dict ./data/dictionary_index --n_basis 10 --emsize 200
# ~/anaconda3/bin/python ./src/testing/summarization/cnn_dm_pyrouge.py --input ./data/src/summ_inputs/title/ --checkpoint ./models/czi_neuro100-20200308-163129 --method_set ours+embs --dict ./data/dictionary_index --n_basis 10 --emsize 200
# ~/anaconda3/bin/python ./src/testing/summarization/cnn_dm_pyrouge.py --input ./data/src/summ_inputs/title/ --checkpoint ./models/czi_neuro100-20200301-223241 --method_set ours+embs --dict ./data/dictionary_index --n_basis 100 --emsize 200
# ~/anaconda3/bin/python ./src/testing/summarization/cnn_dm_pyrouge.py --input ./data/src/summ_inputs/title/ --checkpoint ./models/czi_neuro100-20200301-223241 --method_set ours --dict ./data/dictionary_index --n_basis 100 --emsize 200
# ~/anaconda3/bin/python ./src/testing/summarization/cnn_dm_pyrouge.py --input ./data/src/summ_inputs/article_is_abs/ --checkpoint ./models/czi_neuro100-20200308-163129 --method_set ours+embs --dict ./data/dictionary_index --n_basis 10 --emsize 200
# ~/anaconda3/bin/python ./src/testing/summarization/cnn_dm_pyrouge.py --input ./data/src/summ_inputs/article_is_abs/ --checkpoint ./models/czi_neuro100-20200301-223241 --method_set ours+embs --dict ./data/dictionary_index --n_basis 100 --emsize 200 --outf_vis eval_log/summ_vis/summ_ours.json
# ~/anaconda3/bin/python ./src/testing/summarization/cnn_dm_pyrouge.py --input ./data/src/summ_inputs/article_is_abs/ --checkpoint ./models/czi_neuro100-20200301-223241 --method_set ours+embs --dict ./data/dictionary_index --n_basis 100 --emsize 200 --top_k_max 5 --outf_vis eval_log/summ_vis/summ_ours_abstract.json
# ~/anaconda3/bin/python ./src/testing/summarization/cnn_dm_pyrouge.py --input ./data/src/summ_inputs/article_is_abs/ --checkpoint ./models/czi_neuro100-20200301-223241 --method_set ours --dict ./data/dictionary_index --n_basis 100 --emsize 200
# ~/anaconda3/bin/python ./src/testing/summarization/cnn_dm_pyrouge.py --input ./data/src/summ_inputs/test/ --checkpoint ./models/czi_neuro100-20200301-223241 --method_set ours+embs --dict ./data/dictionary_index --n_basis 100 --emsize 200 --outf_vis eval_log/summ_vis/test.json
#~/anaconda3/bin/python ./src/testing/summarization/cnn_dm_pyrouge.py --input ./data/src/summ_inputs/test --checkpoint ./models/czi_neuro100-20200308-163129 --method_set ours+embs --dict ./data/dictionary_index --n_basis 10 --emsize 200 --outf_vis eval_log/summ_vis/test.json
# ~/anaconda3/bin/python ./src/testing/summarization/cnn_dm_pyrouge.py --input ./data/src/summ_inputs/test2 --checkpoint ./models/czi_neuro100-20200308-163129 --method_set ours+embs --dict ./data/dictionary_index --n_basis 10 --emsize 200 --outf_vis eval_log/summ_vis/test2.json
# ~/anaconda3/bin/python ./src/testing/summarization/cnn_dm_pyrouge.py --input ./data/src/summ_inputs/test2 --checkpoint ./models/czi_neuro100-20200301-223241 --method_set ours+embs --dict ./data/dictionary_index --n_basis 100 --emsize 200 --outf_vis eval_log/summ_vis/test2.json
# ~/anaconda3/bin/python ./src/testing/summarization/cnn_dm_pyrouge.py --input ./data/src/summ_inputs/sample/ --checkpoint ./models/czi_neuro100-20200308-163129 --method_set ours+embs --dict ./data/dictionary_index --n_basis 10 --emsize 200 --outf_vis eval_log/summ_vis/sample.json
# ~/anaconda3/bin/python ./src/testing/summarization/cnn_dm_pyrouge.py --input ./data/src/summ_inputs/abs_title_cit_w_rand --checkpoint ./models/czi_neuro100-20200308-163129 --method_set ours+embs --dict ./data/dictionary_index --n_basis 10 --emsize 200 --outf_vis eval_log/summ_vis/map.json
# ~/anaconda3/bin/python ./src/testing/summarization/cnn_dm_pyrouge.py --input ./data/src/summ_inputs/abs_title_cit_w_rand --checkpoint ./models/czi_neuro100-20200308-163129 --method_set ours+embs --dict ./data/dictionary_index --n_basis 10 --emsize 200 --outf_vis eval_log/summ_vis/map_rank.json
# ~/anaconda3/bin/python ./src/testing/summarization/cnn_dm_pyrouge.py --input ./data/src/summ_inputs/abs_title_cit_w_rand --checkpoint ./models/czi_neuro100-20200301-223241 --method_set ours+embs --dict ./data/dictionary_index --n_basis 100 --emsize 200 --outf_vis eval_log/summ_vis/map_100.json
# ~/anaconda3/bin/python ./src/testing/summarization/cnn_dm_pyrouge.py --input ./data/src/summ_inputs/abs_title_cit_w_rand --checkpoint ./models/czi_neuro100-20200301-223241 --method_set ours+embs --dict ./data/dictionary_index --n_basis 100 --emsize 200 --outf_vis eval_log/summ_vis/map_rank_100.json
# ~/anaconda3/bin/python ./src/testing/summarization/cnn_dm_pyrouge.py --input ./data/src/summ_inputs/cit_title_abs_w_rand --checkpoint ./models/czi_neuro100-20200308-163129 --method_set ours+embs --dict ./data/dictionary_index --n_basis 10 --emsize 200 --outf_vis eval_log/summ_vis/map_reverse_rank.json
# ~/anaconda3/bin/python ./src/testing/summarization/cnn_dm_pyrouge.py --input ./data/src/summ_inputs/cit_title_abs_w_rand --checkpoint ./models/czi_neuro100-20200301-223241 --method_set ours+embs --dict ./data/dictionary_index --n_basis 100 --emsize 200 --outf_vis eval_log/summ_vis/map_reverse_rank_100.json
# ~/anaconda3/bin/python ./src/testing/summarization/cnn_dm_pyrouge.py --input ./data/src/summ_inputs/abs_title_cit_w_rand --checkpoint ./models/czi_neuro100-20200301-223241 --method_set bert --dict ./data/processed/czi_bert_min100/dictionary_index --n_basis 100 --emsize 200 --outf_vis eval_log/summ_vis/map_bert_new.json
# ~/anaconda3/bin/python ./src/testing/summarization/cnn_dm_pyrouge.py --input ./data/src/summ_inputs/cit_title_abs_w_rand --checkpoint ./models/czi_neuro100-20200301-223241 --method_set bert --dict ./data/processed/czi_bert_min100/dictionary_index --n_basis 100 --emsize 200 --outf_vis eval_log/summ_vis/map_reverse_bert_new.json
# ~/anaconda3/bin/python ./src/testing/summarization/cnn_dm_pyrouge.py --input ./data/src/summ_inputs/debug --checkpoint ./models/czi_neuro100-20200301-223241 --method_set bert+embs --dict ./data/dictionary_index --n_basis 100 --emsize 200 --outf_vis eval_log/summ_vis/debug.json
# ~/anaconda3/bin/python ./src/testing/summarization/cnn_dm_pyrouge.py --input ./data/src/summ_inputs/abs_title_cit_w_rand --checkpoint ./models/czi_neuro100-20200301-223241 --method_set ours+sentvec --dict ./data/dictionary_index --n_basis 100 --emsize 200 --outf_vis eval_log/summ_vis/map_sentvec_100.json
# ~/anaconda3/bin/python ./src/testing/summarization/cnn_dm_pyrouge.py --input ./data/src/summ_inputs/abs_title_cit_w_rand --checkpoint ./models/czi_neuro100-20200301-223241 --method_set sentvec --dict ./data/dictionary_index --n_basis 100 --emsize 200 --outf_vis eval_log/summ_vis/map_sentvec.json
# ~/anaconda3/bin/python ./src/testing/summarization/cnn_dm_pyrouge.py --input ./data/src/summ_inputs/abs_title_cit_w_rand --checkpoint ./models/czi_neuro100-20200308-163129 --method_set ours --dict ./data/dictionary_index --n_basis 10 --emsize 200 --outf_vis eval_log/summ_vis/map_10.json
# ~/anaconda3/bin/python ./src/testing/summarization/cnn_dm_pyrouge.py --input ./data/src/summ_inputs/cit_title_abs_w_rand --checkpoint ./models/czi_neuro100-20200301-223241 --method_set sentvec --dict ./data/dictionary_index --n_basis 100 --emsize 200 --outf_vis eval_log/summ_vis/map_reverse_sentvec.json
# ~/anaconda3/bin/python ./src/testing/summarization/cnn_dm_pyrouge.py --input ./data/src/summ_inputs/article_is_abs/ --checkpoint ./models/czi_neuro100-20200308-163129 --method_set bert+sentvec --dict ./data/processed/czi_bert_min100/dictionary_index --n_basis 10 --emsize 200 --outf_vis eval_log/summ_vis/summ_bert_sentvec.json
# ~/anaconda3/bin/python ./src/testing/summarization/cnn_dm_pyrouge.py --input ./data/src/summ_inputs/article_is_abs/ --checkpoint ./models/czi_neuro100-20200308-163129 --method_set bert+sentvec --dict ./data/processed/czi_bert_min100/dictionary_index --n_basis 10 --emsize 200 --top_k_max 5 --outf_vis eval_log/summ_vis/summ_bert_sentvec_abstract.json
~/anaconda3/bin/python ./src/testing/summarization/cnn_dm_pyrouge.py --input ./data/src/summ_inputs/sample --checkpoint ./models/czi_neuro100-20200308-163129 --method_set bert+sentvec --dict ./data/processed/czi_bert_min100/dictionary_index --n_basis 10 --emsize 200 --top_k_max 5 --outf_vis eval_log/summ_vis/summ_bert_sentvec_abstract.json
# ~/anaconda3/bin/python ./src/testing/summarization/cnn_dm_pyrouge.py --input ./data/src/summ_inputs/abstract/ --checkpoint ./models/czi_neuro100-20200308-163129 --method_set bert+sentvec --dict ./data/processed/czi_bert_min100/dictionary_index --n_basis 10 --emsize 200 --outf_vis eval_log/summ_vis/summ_full_bert_sentvec.json
